development:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true

test:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true

staging:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'pets_waiting_staging'

production:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'pets_waiting_production'
