development:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'petswaiting.development'

test:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'petswaiting.test'

staging:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'petswaiting.staging'

production:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'petswaiting.com'
    authentication: 'plain'
    enable_starttls_auto: true
  aws_bucket: 'petswaiting.production'
